# Use postgres/example user/password credentials
version: "3.7"

services:

    jupyter:
        container_name: datascience-jupyter
        restart: always
        build:
            context: ./docker/superset
            dockerfile: Dockerfile
        image: "jupyter"
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=yes
        volumes:
            - //c/Users/Alessandro/Documents/datascience/notebooks:/home/jovyan/work 

    minio:
        container_name: datascience-minio
        restart: always
        image: "minio/minio:latest"
        ports:
            - "9000:9000"
        environment:
            - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
            - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        command: server /data
        volumes:
            - //c/Users/Alessandro/Documents/datascience/data/minio:/data

    redis:
        container_name: datascience-redis
        restart: always
        image: "redis:5.0.7"
        ports:
            - "6379:6379"
        volumes:
            - //c/Users/Alessandro/Documents/datascience/etc/redis.conf:/usr/local/etc/redis/redis.conf
            - //c/Users/Alessandro/Documents/datascience/data/redis:/data

    postgres:
        container_name: datascience-postgres
        restart: always
        image: postgres:12.1
        ports:
            - "5432:5432"
        environment:
            - DEBUG=false
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - //c/Users/Alessandro/Documents/datascience/data/postgresql:/var/lib/postgresql
 
    adminer:
        container_name: datascience-adminer
        restart: always
        image: adminer
        restart: always
        ports:
            - "8080:8080"

    superset:
        container_name: datascience-superset
        restart: always
        build:
            context: ./docker/superset
            dockerfile: Dockerfile
        image: "superset"
        ports:
            - "8089:8088"
        volumes:
            - //c/Users/Alessandro/Documents/datascience/data/superset:/home/superset/.superset
