version: "3.7"

services:

    jupyter:
        container_name: datascience-jupyter
        restart: always
        build:
            context: ./docker/jupyter
            dockerfile: Dockerfile
        image: "jupyter"
        ports:
            - "8888:8888"
        environment:
            - JUPYTER_ENABLE_LAB=yes
        volumes:
            - ./notebooks:/home/jovyan/work 

    superset:
        container_name: datascience-superset
        restart: always
        build:
            context: ./docker/superset
            dockerfile: Dockerfile
        image: "superset"
        ports:
            - "8088:8088"
        volumes:
            - superset:/home/superset/.superset

    minio:
        container_name: datascience-minio
        restart: always
        image: "minio/minio:latest"
        ports:
            - "9000:9000"
        environment:
            - MINIO_ACCESS_KEY=minio
            - MINIO_SECRET_KEY=minio123!
        command: server /data
        volumes:
            - minio:/data

    redis:
        container_name: datascience-redis
        restart: always
        image: "redis:5.0.7"
        ports:
            - "6379:6379"
        volumes:
            - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
            - redis:/data

    redisinsight:
        container_name: datascience-redisinsight
        restart: always
        image: "redislabs/redisinsight"
        ports:
            - "8001:8001"
        volumes:
            - redisinsight:/db

    adminer:
        container_name: datascience-adminer
        restart: always
        image: adminer
        ports:
            - "8080:8080"

    postgres:
        container_name: datascience-postgres
        restart: always
        build:
            context: ./docker/postgresql
            dockerfile: Dockerfile
        image: "postgresql"
        ports:
            - "5432:5432"
        environment:
            - DEBUG=false
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data

    mongodb:
        container_name: datascience-mongodb
        restart: always
        image: "mongo:4.0.15-xenial"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db

    mongo-express:
        container_name: datascience-mongo-express
        image: "mongo-express:0.49.0"
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_MONGODB_SERVER=datascience-mongodb

volumes:
  minio:
  superset:
  redis:
  redisinsight:
  pgdata:
  mongodb:
